// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcfeCRN5UHFUKhnve-Y_ZPpnftYDNg6cs',
    appId: '1:557652370538:web:79581a28802d01cf5d9613',
    messagingSenderId: '557652370538',
    projectId: 'chatter-app-15118',
    authDomain: 'chatter-app-15118.firebaseapp.com',
    storageBucket: 'chatter-app-15118.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqoSbQmY8FdU6wJMNNUl7Rs2zXPYlPIkA',
    appId: '1:557652370538:android:4768fb02b5dae0ca5d9613',
    messagingSenderId: '557652370538',
    projectId: 'chatter-app-15118',
    storageBucket: 'chatter-app-15118.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Vg8UekAQUaCxZCIwVOz1hD2PsoUqLnk',
    appId: '1:557652370538:ios:36070fc6b2b075ec5d9613',
    messagingSenderId: '557652370538',
    projectId: 'chatter-app-15118',
    storageBucket: 'chatter-app-15118.appspot.com',
    iosBundleId: 'com.example.chatService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Vg8UekAQUaCxZCIwVOz1hD2PsoUqLnk',
    appId: '1:557652370538:ios:36070fc6b2b075ec5d9613',
    messagingSenderId: '557652370538',
    projectId: 'chatter-app-15118',
    storageBucket: 'chatter-app-15118.appspot.com',
    iosBundleId: 'com.example.chatService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcfeCRN5UHFUKhnve-Y_ZPpnftYDNg6cs',
    appId: '1:557652370538:web:7beaacfb8e069b8d5d9613',
    messagingSenderId: '557652370538',
    projectId: 'chatter-app-15118',
    authDomain: 'chatter-app-15118.firebaseapp.com',
    storageBucket: 'chatter-app-15118.appspot.com',
  );
}
